# Generated by Django 3.1.6 on 2021-02-17 08:50

import articles.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20210217_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=articles.models.articles_image_path),
        ),
    ]
